application: amusejsmixer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*\.css)
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: public/\1
  upload: public/(.*\.js)

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: public/\1
  upload: public/(.*\.(mid|midi|mp3|wav))  

libraries:
- name: webapp2
  version: "2.5.2"